server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: false
        format_sql: true
    open-in-view: false

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: krleicablog-bucket
      default-url: https://krleicablog-bucket.s3.ap-northeast-2.amazonaws.com/

iamAccessKey: AKIA5HGLAWUGSAFOUSTQ
iamSecretKey: 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