spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 93377060108-pa2ji2tilusvmlspaem2e7c7vdatoseh.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            client-id: mQVojDrG3Q_eP2jzbyPl
            client-secret: QJ4eVonUPT

            #  인가 코드 전달
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            # access token 요청 uri
            token-uri: https://nid.naver.com/oauth2.0/token

            # user 정보 요청 uri
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response



# cors 설정
cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600


# jwt secret key 설정
jwt:
  secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect
